config/routes.rb
Rails.application.routes.draw do

  resources :gps


  namespace :api do # Ruta para la api 
  	namespace :v1 do # Ruta para la version a consumir
  		resources :gps, only: [:create, :show]
  	end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gp.rb
class Gp < ApplicationRecord
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/gps_controller.rb
class Api::V1::GpsController < Api::V1::ApplicationController
  before_action :set_gp, only: [:show]

  def show
  end

  def create
    @gp = Gp.new(gp_params)

    respond_to do |format|
      if @gp.save
        format.json { render :show, status: :created, location: @gp }
      else
        format.json { render json: @gp.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gp
      @gp = Gp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gp_params
      params.require(:gp).permit(:latitude, :longitude, :sent_at, :vehicle_identifier)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gps_controller.rb
class GpsController < ApplicationController
  before_action :set_gp, only: [:show, :edit, :update, :destroy]

  # GET /gps
  # GET /gps.json
  def index
    @gps = Gp.all
  end

  # GET /gps/1
  # GET /gps/1.json
  def show
  end

  # GET /gps/new
  def new
    @gp = Gp.new
  end

  # GET /gps/1/edit
  def edit
  end

  # POST /gps
  # POST /gps.json
  def create
    @gp = Gp.new(gp_params)

    respond_to do |format|
      if @gp.save
        format.html { redirect_to @gp, notice: 'Gp was successfully created.' }
        format.json { render :show, status: :created, location: @gp }
      else
        format.html { render :new }
        format.json { render json: @gp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gps/1
  # PATCH/PUT /gps/1.json
  def update
    respond_to do |format|
      if @gp.update(gp_params)
        format.html { redirect_to @gp, notice: 'Gp was successfully updated.' }
        format.json { render :show, status: :ok, location: @gp }
      else
        format.html { render :edit }
        format.json { render json: @gp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gps/1
  # DELETE /gps/1.json
  def destroy
    @gp.destroy
    respond_to do |format|
      format.html { redirect_to gps_url, notice: 'Gp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gp
      @gp = Gp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gp_params
      params.require(:gp).permit(:latitude, :longitude, :sent_at, :vehicle_identifier)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gps_helper.rb
module GpsHelper
end

app/views/gps/_form.html.erb
<%= form_for(gp) do |f| %>
  <% if gp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gp.errors.count, "error") %> prohibited this gp from being saved:</h2>

      <ul>
      <% gp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :sent_at %>
    <%= f.datetime_select :sent_at %>
  </div>

  <div class="field">
    <%= f.label :vehicle_identifier %>
    <%= f.text_field :vehicle_identifier %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gps/edit.html.erb
<h1>Editing Gp</h1>

<%= render 'form', gp: @gp %>

<%= link_to 'Show', @gp %> |
<%= link_to 'Back', gps_path %>

app/views/gps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gps</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Sent at</th>
      <th>Vehicle identifier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gps.each do |gp| %>
      <tr>
        <td><%= gp.latitude %></td>
        <td><%= gp.longitude %></td>
        <td><%= gp.sent_at %></td>
        <td><%= gp.vehicle_identifier %></td>
        <td><%= link_to 'Show', gp %></td>
        <td><%= link_to 'Edit', edit_gp_path(gp) %></td>
        <td><%= link_to 'Destroy', gp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gp', new_gp_path %>

app/views/gps/new.html.erb
<h1>New Gp</h1>

<%= render 'form', gp: @gp %>

<%= link_to 'Back', gps_path %>

app/views/gps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @gp.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @gp.longitude %>
</p>

<p>
  <strong>Sent at:</strong>
  <%= @gp.sent_at %>
</p>

<p>
  <strong>Vehicle identifier:</strong>
  <%= @gp.vehicle_identifier %>
</p>

<%= link_to 'Edit', edit_gp_path(@gp) %> |
<%= link_to 'Back', gps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>